language: node_js
node_js:
- 8.0.0
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  local_dir: build
  token:
    secure: Nw45rl0dIRiE660jw/QKJI+5Emhi+LUBRJY285oi1wV2VkVhvRXSscuKmnXijyzlokfgsCIiTPMFOXidkVMC8IHUVmqqtanrHDlr9lBosZGv/IB+BYDOxcUCTUGheEV74i2RGsvVo0c/+BBjC8nss/7ZlkhN+sen2Il14/1fG0fOMBvl/y6FAUP8YWJ/fZwSzuvCD4Gtrxi8/hDTATjYd1KInfJSGpoxOJbxXLMz+R2fqkTMB79YZ7pPy0k0O0+0fbSZ93ZnxS7Evd7xXlZfSC+fnGRpIf/VpEegDGdzDsiFjWsFC//w1MqE63EyTjDNr5XGm+ktAw6u0o/NJEnjHa59MWke/TxyPQqC8EClVUUtCwXED1dzLHSrzZDGitNfbwYlnU9wT2lzZRp2rk5CDME977C6e+0shMi7jTiuWUINE3adk/4kw/Dmpa89brWu/WGKYVEQGe7HrzNMvGL2/GbSweiW3+Y59M7SM9GwygaHayQmoFFSrO79DXYGt6dS2xjPKjeE8ZpA5X5k4M0EpIU2QMDArKe7wHASipnD8tb8QSP4bxOyuqJP5EVWPAtnvoRqUdr1GLbOqpobSH1jByNS9mvvstXct4RWZavVduyDWYN/jDCTgRtAmljktkTfJ0GBKukHKpsrGw5mEUC3QUbbbJ6MxBpgQHVzvpUdxds=
  project: send-money-challenge
