language: node_js
node_js:
- 8.0.0
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  local_dir: build
  token:
    secure: d7eGEWf4Y0KLMkA2Mdl7GvcPnEYnCkjQn7PlahoVhp+85y/rn/jUCib0TsaCjz1cutdumO9pVVwRt9Srn12pN0tNDh89UCq/cQNLxJ4y/MzQm8u9K8zmyl6NzzdAOS+25TBmSULSBD6fI+uPnko2GD6TuSeJ+aSH9qxhuzFl3wX/YPZ2bfJ/MLliVsdww+Onp1pCkRoxoQIhFSZ1y8Elj71TJMaRyjKGzgExF8+obWBxYWn+2jT1ZorHlcsPB8xYfxlEh1EWkZ/Ez47bZNtPp7lVSFSQwInWHt2MzCBdB6ZlYuDFDFuEoAMk2GLZtWTEzgPXfDFDzBJr6+G09TEBUGXplbz+yRJLIOq8vf9JpdpcCJSm95av2VysjOrbPWFfoHb3S+iKZf+ihSY4dIWX2cgQ/SxWz08VW6LuSJEXL1ueCMDHoQsnmiN+Rwo1Nxrn4i3arN8D6MqHlwjEOjWn7hNsyoftXwy0jkdfN90ukD4o1mbCLXuzRYrkdszFWNLLP4oJMRW80cjIV5Rh3h7fwZmjplbuk4tI21R/rnkYOJ5ykXz9pEI+tj+0cb5Uo3bkM54hCCw3qf54xFSlRWw90x5UEYAwIiSlDwfmmnj1o5WGGpRBHWW0AQiy2llUrKOvzzWx6DmqVq8W+FWG5+LmS1vYo/LpoV33+MEvsB+mgkk=
  project: send-money-challenge
