language: node_js
node_js:
- "node"
cache:
  directories:
  - "node_modules"
before_script:
  - npm install -g firebase-tools
script:
- npm test
- npm run build
after_success:
  - firebase use --token $REACT_APP_FIREBASE_TOKEN send-money-challenge
  - firebase deploy --non-interactive --token $REACT_APP_FIREBASE_TOKEN
